In [5]:
import pandas as pd
from sklearn.model_selection import StratifiedShuffleSplit as strat_split

In [17]:
base = pd.read_csv("base_de_dados/base.csv", sep = ";")

In [19]:
base

    cod genero  prova1  prova2  idade raça
0     1      F     5.9     7.7     23   pd
1     2      F     7.1     7.9     20   pd
2     3      F     9.0     9.0     35   pd
3     4      M     7.5     8.0     35   bc
4     5      M     7.5     7.5     27   bc
5     6      F     3.0     8.3     18   pd
6     7      M    10.0     8.3     23   pt
7     8      M     6.7     6.5     25   pd
8     9      F     9.7     9.5     35   pd
9    10      F     5.6     7.2     27   pt
10   11      M     7.0     7.0     41   bc
11   12      M     8.9     7.5     18   bc
12   13      F    10.0    10.0     18   pd
13   14      F     7.9     9.7     30   bc
14   15      F     8.0     8.0     34   pt
15   16      M     7.2     8.0     22   pd
16   17      F     6.9     4.5     20   pd
17   18      F     9.5     9.0     37   pd
18   19      M     4.7     7.0     23   bc
19   20      M     7.0     7.8     22   bc
20   21      F     9.0     9.8     37   pt
21   22      F     6.7     4.9     26   bc

In [21]:
base["genero"].value_counts()

genero
F    13
M     9
Name: count, dtype: int64

In [23]:
(13 / len(base), 9 / len(base))

(0.5909090909090909, 0.4090909090909091)

In [25]:
0.5909090909090909 + 0.4090909090909091

1.0

In [31]:
divisao = strat_split(test_size = 0.3)

for treinamento, teste in divisao.split(base, base["genero"]):
    df_trein = base.iloc[treinamento]
    df_teste = base.iloc[teste]

In [33]:
df_trein.shape, df_teste.shape

((15, 6), (7, 6))

In [35]:
df_teste

    cod genero  prova1  prova2  idade raça
13   14      F     7.9     9.7     30   bc
9    10      F     5.6     7.2     27   pt
15   16      M     7.2     8.0     22   pd
4     5      M     7.5     7.5     27   bc
0     1      F     5.9     7.7     23   pd
7     8      M     6.7     6.5     25   pd
5     6      F     3.0     8.3     18   pd